import React, { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Download, X } from 'lucide-react';

/**
 * Tiny banner that appears when a new service-worker version is ready.
 * Tapping "Refresh" reloads with the updated bundle.
 *
 * Uses dynamic import so the build still succeeds in dev (where the SW
 * helper isn't generated by vite-plugin-pwa).
 */
export function PWAUpdatePrompt() {
  const [needRefresh, setNeedRefresh] = useState(false);
  const [updateSW, setUpdateSW] = useState<((reload?: boolean) => Promise<void>) | null>(null);

  useEffect(() => {
    // Only attempt SW registration in production builds
    if (import.meta.env.DEV) return;

    let cancelled = false;
    // @ts-expect-error — virtual module created by vite-plugin-pwa at build time
    import('virtual:pwa-register')
      .then(({ registerSW }) => {
        if (cancelled) return;
        const sw = registerSW({
          immediate: true,
          onNeedRefresh() { setNeedRefresh(true); },
        });
        setUpdateSW(() => sw);
      })
      .catch(() => {
        // PWA module unavailable (dev or unsupported browser) — silently skip.
      });
    return () => { cancelled = true; };
  }, []);

  if (!needRefresh) return null;

  return (
    <AnimatePresence>
      <motion.div
        initial={{ y: 80, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        exit={{ y: 80, opacity: 0 }}
        className="fixed bottom-20 md:bottom-6 left-4 right-4 md:left-auto md:right-6 md:max-w-sm z-[60] bg-gradient-to-r from-blue-600 to-indigo-700 text-white rounded-2xl shadow-2xl p-4 flex items-center gap-3"
      >
        <div className="w-10 h-10 rounded-xl bg-white/20 flex items-center justify-center shrink-0">
          <Download size={18} />
        </div>
        <div className="flex-1 min-w-0">
          <p className="text-sm font-bold">Versi baru tersedia</p>
          <p className="text-[11px] text-blue-100/80">Refresh untuk dapat ciri terkini</p>
        </div>
        <button
          onClick={() => updateSW?.(true)}
          className="bg-white text-blue-700 px-3 py-1.5 rounded-lg text-[10px] font-bold uppercase tracking-widest hover:bg-blue-50 transition-all shrink-0"
        >
          Refresh
        </button>
        <button
          onClick={() => setNeedRefresh(false)}
          className="p-1.5 rounded-lg text-white/70 hover:text-white shrink-0"
          title="Lain kali"
        >
          <X size={16} />
        </button>
      </motion.div>
    </AnimatePresence>
  );
}
